### ISSUE TITLE
windows installer issue

### ISSUE THREAD

**Issue by presscott1gss2** [kirb/LegacyUpdate#106] opened 2023-01-26 18:56 UTC
i have a problem whit windows installer after i install the update the windows installer no longer works it keeps cshowing an error i tried many ways to fix it but it dosent work plzz fix it

**Comment by renodr** [comment] 2023-01-28 15:39
We could use some more information to investigate this

Which version of Windows are you using?

Have you tried doing "msiexec /unregister" and "msiexec /regserver"?

**Comment by presscott1gss2** [comment] 2023-01-28 20:41
Hi i have a pirated version of Windows îs called Tiny XP beast edition its runing sp3 and i tried starting the Windows installer services but dosent works maybe If i install an original copy runing sp2?

**Comment by kirb** [comment] 2023-02-01 07:59
Is the Background Intelligent Transfer Service enabled? I played around with TinyXP and found that the more extreme service configurations it provides will disable BITS in addition to Automatic Updates and Windows Installer. If you use one of those configurations and then manually re-enable Automatic Updates, also re-enable Windows Installer and BITS. There might also be other services that need to be enabled to get the correct updates returned by the server, such as Windows Management Instrumentation (WMI), and others that might be needed for specific patches to successfully install.

**Comment by kirb** [comment] 2023-08-16 06:01
Going to close this because we never heard back from the original poster, and I wasn't able to reproduce the issue.

**Closed by kirb** 2023-08-16 06:01 UTC
