### ISSUE TITLE
Desktop shortcut does not work after installation on Windows 2000

### ISSUE THREAD

**Issue by E-System33** [kirb/LegacyUpdate#110] opened 2023-01-29 10:49 UTC
Hello, 👋😅

After installing the patch I get the following message when I try to open the update page with Windows 2000 Pro (french install).

![image](https://user-images.githubusercontent.com/89921808/215320541-80323cc2-b9d3-42e4-b1e0-29fb0a991e91.png)
( An approximate translation)
"Mapping between account name and  security ID has not been done"

I tried again by disabling some option on the installer but it did nothing.

Config:
Computer: VMware Workstation PRO 17 VM (VMwareTool: installed)
RAM: 500 mb
IE Ver: 
![image](https://user-images.githubusercontent.com/89921808/215320878-744dceff-dd33-43ae-9d3d-cedbe2a04630.png)
Legacy Update Ver: 1.6.2
WIndows infos: 
![image](https://user-images.githubusercontent.com/89921808/215320950-576fd2e6-ca72-4178-b2ef-39a280e1f5ac.png)

If there is a way to correct this, I would be very thankful :)

Thank you 😁

**Comment by E-System33** [comment] 2023-01-29 12:03
I was finally able to access the page by going manually using the link on IE 6.
http://legacyupdate.net/

I installed the update that allows Windows Update to work, but after a restart I only got an unknown error.

So I loaded a backup of the VM and try again the manipulation and it worked !

![image](https://user-images.githubusercontent.com/89921808/215324678-3b263ad0-5e2f-4d27-a097-bd93f936d09a.png)
****

After launching Windows Update using the link manually, it made the start menu shortcut work again. 🤔

**Comment by stdin82** [comment] 2023-01-29 12:27
Is it fresh installation? did you launch IE6 once before installing LegacyUpdate?

**Comment by E-System33** [comment] 2023-01-30 18:07
> Is it fresh installation? did you launch IE6 once before installing LegacyUpdate?

Yes

**Comment by kirb** [comment] 2023-08-16 05:50
Going to close this as a duplicate of #159, the workaround is to restart Windows.

**Closed by kirb** 2023-08-16 05:50 UTC
