### ISSUE TITLE
Error when trying to use on Windows 8.1 pro

### ISSUE THREAD

**Issue by IHS5452** [kirb/LegacyUpdate#135] opened 2023-03-23 17:31 UTC
It looks like there is an error when trying to apply the updates when using Windows 8.1 pro. 

![error](https://user-images.githubusercontent.com/25617647/227289105-f16fc65a-76ad-413d-8496-7c7658454f1f.PNG)

The Windows 8.1 Pro ISO i used to install was downloaded directly from Microsoft's website: https://www.microsoft.com/en-us/software-download/windows8ISO

**Comment by renodr** [comment] 2023-03-24 01:39
I think this might be a duplicate of #112 and #104

**Comment by renodr** [comment] 2023-05-12 18:17
@kirb this should be able to get closed since #139 has been merged

**Comment by kirb** [comment] 2023-05-13 02:16
Thanks :+1:

Will be fixed in Legacy Update 1.7.

**Closed by kirb** 2023-05-13 02:16 UTC
