### ISSUE TITLE
Legacy Update crashes mid-install. Can't be opened anymore.

### ISSUE THREAD

**Issue by gingusScringus** [kirb/LegacyUpdate#203] opened 2023-11-17 12:38 UTC
Another problem I got, this time with Legacy Update crashed for some reason after restarting and trying to install the updates, it showed a "stopped working" message and once i clicked on close application, it takes me to the desktop.

I tried running Legacy Update again, but it doesn't work anymore.
![image](https://github.com/kirb/LegacyUpdate/assets/67906219/4a9670ef-4781-4ed1-9651-e173000d5dc9)

Funnily enough, this problem is similar to what [Michael MJD](https://youtu.be/5faA4ph4Fo8?t=228) encountered when he tried to install Legacy Update on a WIndows XP VM, only this time I didn't even install ANY Service Packs on the Windows 7 VM. I don't know, for some reason this 1.8 version causes more problems than i had in the past versions.

**Comment by kirb** [comment] 2023-11-17 12:42
Sorry for the issue, it's specifically a bug with the Enable Microsoft Update feature. You can try again with that unchecked and it'll work.

Closing this issue since it's a duplicate of #186.

**Closed by kirb** 2023-11-17 12:42 UTC
