### ISSUE TITLE
Legacy Update creates the LegacyUpdateTemp user account with password

### ISSUE THREAD

**Issue by gingusScringus** [kirb/LegacyUpdate#202] opened 2023-11-17 12:27 UTC
Happened when I tried to install Legacy Update on a Windows 7 VM as I was installing a Service Pack for me to be able to install VMware Tools on the VM. I set up a password on my main gingusScringus user account, and when the Legacy Update restarts the computer, it gave me a user selection. I tried to access the temp user, but since it's locked, I couldn't access it. So I had to do the sethc.exe hack just to change the password. Legacy Update version's 1.8 in case anybody wondering.
![Screenshot 2023-11-17 192122](https://github.com/kirb/LegacyUpdate/assets/67906219/31b84b63-4311-4639-8769-f03ecd827952)
(forgot to take a screenshot for the login to the temp account)

**Comment by kirb** [comment] 2023-11-17 12:44
Why did you need to break into the LegacyUpdateTemp account? There's nothing interesting there, I guess.

Since you hit the Enable Microsoft Update bug in #203, the user wasn't cleaned up. You can run Legacy Update setup again, and then immediately click Cancel, to have it clean up the temp user for you.

Closing since this doesn't seem to be a bug report, this is expected behavior.

**Closed by kirb** 2023-11-17 12:44 UTC

**Comment by IanMunster** [comment] 2023-11-20 13:06
I have the same problem. 
Legacy Update crashed mid update, I tried reinstalling it, but it crashed again on the desktop.
Now I made the error to switch account and manually remove the LegacyTemp account.
After a restart only the temp account is active, my main user account is gone and I can't login to the temp account due to not knowing the password.
Please help
